import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col bg-gray-900">
          <div className="border-b-2 border-gray-800 p-2 flex flex-row z-20">
                <div className="bg-red-600 w-3 h-3 rounded-full mr-2"></div>
                <div className="bg-yellow-500 w-3 h-3 rounded-full mr-2"></div>
                <div className="bg-green-500 w-3 h-3 rounded-full mr-2"></div>
            </div> 
            {children}
        </div>
      </body>
    </html>
  );
}
